# Generated by Django 5.2.4 on 2025-07-06 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='eleccion.seccion')),
            ],
        ),
    ]
