# Generated by Django 5.2.4 on 2025-07-06 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0004_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido_politico', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('candidato_id', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_cargo', to='eleccion.cargo')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_eleccion', to='eleccion.eleccion')),
            ],
        ),
    ]
