# Generated by Django 5.2.4 on 2025-07-06 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0005_candidatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefe_id', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='eleccion.eleccion')),
            ],
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('elecciones', models.ManyToManyField(related_name='recintos', through='eleccion.Mesa', to='eleccion.eleccion')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='eleccion.recinto'),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('numero', 'recinto', 'eleccion')},
        ),
    ]
