# Generated by Django 5.1.7 on 2025-07-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0006_mesa_recinto_mesa_recinto_alter_mesa_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recinto',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recintos', to='eleccion.seccion'),
        ),
    ]
