# Generated by Django 5.1.7 on 2025-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0007_recinto_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
