# Generated by Django 5.1.7 on 2025-07-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0008_mesa_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.BooleanField(default=False)),
                ('votante_id', models.IntegerField()),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votantes', to='eleccion.eleccion')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votantes', to='eleccion.mesa')),
            ],
        ),
    ]
