# Generated by Django 5.1.7 on 2025-07-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0009_votante'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
