# Generated by Django 5.2.2 on 2025-07-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0010_seccion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='jefe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
