# Generated by Django 5.2.2 on 2025-07-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0011_alter_mesa_jefe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatura',
            name='candidato_id',
        ),
        migrations.AddField(
            model_name='candidatura',
            name='candidato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
