# Generated by Django 5.2.4 on 2025-07-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleccion', '0012_remove_candidatura_candidato_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='eleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='eleccion.eleccion'),
        ),
    ]
