# Generated by Django 5.2.4 on 2025-07-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa_id', models.IntegerField()),
                ('votante_id', models.IntegerField()),
                ('candidatura_id', models.IntegerField()),
                ('eleccion_id', models.IntegerField()),
            ],
        ),
    ]
