# Generated by Django 5.2.4 on 2025-07-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='cargo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
